services:
  frontend:
    build: ./Frontend
    ports:
      - "80:80"
    restart: unless-stopped

  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000  
    restart: unless-stopped

networks:
  default:
    name: app-network
    driver: bridge