services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    restart: unless-stopped

# Опционально, если сервисы должны общаться:
networks:
  default:
    name: app-network
    driver: bridge